### ISSUE TITLE
Can we modify makefile to be the same as stockfish' makefile?

### ISSUE THREAD

**Issue by abdulbadii** [AndyGrant/Ethereal#102]
Can we modify makefile to be the same as stockfish' makefile but few ones tell/notify users this is building Ethereal binary...

**Comment by AndyGrant** [comment]
What exactly are you looking for? Ethereal's make file is very simple. We have three targets, ``nopopcnt``, ``popcnt`` and ``pext``. All we need is ``make <target=popcnt>`` to build. The stockfish makefile is far more complex

**Comment by abdulbadii** [comment]
The stockfish makefile is far more complex at the sane time, actually more simpler as it is far more systematically organized, you'll convert it in minute.

**Comment by AndyGrant** [comment]
I have no interest in changing the makefile, unless there is something to gain in specific.

**Comment by abdulbadii** [comment]
If one does will it be accepted on PR?

**Comment by AndyGrant** [comment]
If you want to modify the makefile, Ill certainly look at the end result and consider it.

**Comment by abdulbadii** [comment]
https://github.com/abdulbadii/Ethereal/blob/master/src/Makefile

add TYPE=release or texel or profile for 
RFLAGS, TFLAGS, PFLAGS
respecively

**Comment by AndyGrant** [comment]
I still don't see a reason to just copy paste the SF makefile. The makefile we have now fits the needs that I see for myself, and for testers on OpenBench. Its not about complexity or simplicity, its about demonstrating a need for a chance.  Demonstrating that the current makefile is insufficient in a somewhat common use case.
