### ISSUE TITLE
Ethereal unable to mate with N and B

### ISSUE THREAD

**Issue by tissatussa** [AndyGrant/Ethereal#105]
at the end of the following engine-vs-engine game, Ethereal 11.57 evaluates the position as winning by +9, but it doesn't know how to mate with only knight and bishop .. it lets the opponent king go to the wrong corner .. the game ends with a stalemate .. in this theme game Black should be able to win :

[Event "engine vs engine - theme game"]
[Site "Hengelo, Holland - [https://lichess.org/eSUK0nC1](https://lichess.org/eSUK0nC1)"]
[Date "2019.11.24"]
[White "asmFish 190518"]
[Black "Ethereal 11.57"]
[Result "1/2-1/2"]
[PlyCount "159"]
[SetUp "1"]
[TimeControl "40/300"]
[FEN "rnbqkbnr/ppp1ppp1/8/3p3p/3P1B2/4P3/PPP2PPP/RN1QKBNR b KQkq - 0 1"]

1...e5 2. Bxe5 f6 3. Bf4 g5 4. Be2 gxf4 5. Bxh5+ Ke7 6. exf4 c6 7. Qd3 Qd6 8. Bf3 Qxf4 9. Ne2 Qd6 10. h3 f5 11. c4 Nf6 12. cxd5 cxd5 13. O-O Nc6 14. Nbc3 a6 15. Rfe1 Kd8 16. Rad1 Ne4 17. Qc2 Bd7 18. Qb3 Ne7 19. g3 Bh6 20. Bg2 Rc8 21. Qxb7 Rb8 22. Qa7 Nc8 23. Nxe4 fxe4 24. Qc5 Rxb2 25. Qa5+ Ke8 26. Nc3 Rf8 27. Qxd5 Rfxf2 28. Qg8+ Qf8 29. Rxe4+ Ne7 30. Qxf8+ Kxf8 31. Rf1 Rxf1+ 32. Bxf1 Bd2 33. Ne2 Rxa2 34. Re5 a5 35. Nf4 a4 36. Ne6+ Bxe6 37. Rxe6 Bc3 38. Rf6+ Kg7 39. Rf7+ Kxf7 40. Bc4+ Kf6 41. Bxa2 Bxd4+ 42. Kg2 Nc6 43. Kf3 Nb4 44. Bc4 a3 45. Ke4 Bf2 46. g4 a2 47. g5+ Kxg5 48. Bxa2 Nxa2 49. Kd3 Kh4 50. Kc4 Kxh3 51. Kb3 Nc1+ 52. Kc2 Be3 53. Kc3 Kg4 54. Kc4 Kg5 55. Kd5 Kf5 56. Kd6 Bf4+ 57. Kd5 Be3 58. Kd6 Bf4+ 59. Kd5 Nb3 60. Kc4 Nd2+ 61. Kd4 Ke6 62. Kd3 Kd5 63. Ke2 Ke4 64. Kf2 Nb3 65. Kf1 Kf3 66. Kg1 Nd4 67. Kh1 Bg3 68. Kg1 Nf5 69. Kh1 Bf2 70. Kh2 Nd4 71. Kh1 Bg3 72. Kg1 Bf2+ 73. Kh2 Ne2 74. Kh1 Be3 75. Kh2 Bf2 76. Kh1 Be3 77. Kh2 Bf4+ 78. Kh1 Nd4 79. Kg1 Ne2+ 80. Kh1 Bg3 1/2-1/2

**Comment by AndyGrant** [comment]
Ethereal has not contain special code for these endgames, as they are broadly covered by Sygyzy support. furthermore, local analysis of the position resolves to a mating line in a fairly short period of time.
