### ISSUE TITLE
Ethereal exceeds time and looses

### ISSUE THREAD

**Issue by tissatussa** [AndyGrant/Ethereal#110]
When using Ethereal with CuteChess in a tournament, the engine (v11.75) exceeds the clock time limit -- I tested 5 minutes for 40 moves -- and so it looses the game ?!

I don't know how CuteChess does instruct an engine to limit 40 moves in 5 min, because the UCI protocol only has "fixed depth" / "time per move" / "infinite" when calculating any FEN, but other engines do not seem to have this problem.

**Comment by AndyGrant** [comment]
Can you provide more information about your system, and the configuration of Ethereal?

As any easy fix, Ethereal has a ``MoveOverhead`` setting which can be increased. This resolves issues with time losses on machines with high latency.
