### ISSUE TITLE
Connected pawns mask

### ISSUE THREAD

**Issue by fernandotenorio** [AndyGrant/Ethereal#12]
Hi, 
I'm  reading some of your code to improve my engine Tunguska:
https://github.com/fernandotenorio/Tunguska

I noticed at masks.c, in the connectedPawn mask initialization:

for (int i = 8 ; i < 54; i++){ ... }

Shouldn't it be i < 56?

**Comment by AndyGrant** [comment]
You are absolutely correct! If you would like some form of credit, submit a pull request that fixes that value, and changes https://github.com/AndyGrant/Ethereal/blob/master/src/uci.c#L66 to "Ethereal7.86"

**Comment by fernandotenorio** [comment]
Ok, I think I've done that! If I screwed you can go ahead and fix it, no
need for credits!
Happy christmas =)

2016-12-15 0:40 GMT-02:00 Andrew Grant <notifications@github.com>:

**Comment by AndyGrant** [comment]
Resolved in https://github.com/AndyGrant/Ethereal/pull/13

Thanks for the help!
