### ISSUE TITLE
src/movegen.h missing definition of build* functions 

### ISSUE THREAD

**Issue by bhamadicharef** [AndyGrant/Ethereal#127]
in src/movegen.h missing definition of build* functions 
    void buildEnpassMoves(uint16_t *moves, int *size, uint64_t attacks, int epsq);
    void buildPawnMoves(uint16_t *moves, int *size, uint64_t attacks, int delta);
    void buildPawnPromotions(uint16_t *moves, int *size, uint64_t attacks, int delta);
    void buildNonPawnMoves(uint16_t *moves, int *size, uint64_t attacks, int sq);
    void buildKnightMoves(uint16_t *moves, int *size, uint64_t pieces, uint64_t targets);
    void buildBishopMoves(uint16_t *moves, int *size, uint64_t pieces, uint64_t occupied, uint64_t targets);
    void buildRookMoves(uint16_t *moves, int *size, uint64_t pieces, uint64_t occupied, uint64_t targets);
    void buildKingMoves(uint16_t *moves, int *size, uint64_t pieces, uint64_t targets);

**Comment by AndyGrant** [comment]
Those functions are static, and thus should/could not be declared in ``movegen.h``. The following would work, if you like to see definitions. https://github.com/AndyGrant/EtherealDev/commit/5b12c3734081745049ff6a000765055932cec2fc This adds the function prototypes at the top of ``movegen.c``, and moves the functions to the end of ``movegen.c``. They are still NOT declared/defined in ``movegen.h``

**Comment by bhamadicharef** [comment]
Thanks Andy. I am using your code to make a QtEthereal in A Qt environment and it was complaining about this ...  I am trying to study the memory foot print and resources (operations like data move, add, mul, etc.) required in the view of a hardware accelerated version.
