### ISSUE TITLE
What is typedef jmp_buf in struct Thread ?

### ISSUE THREAD

**Issue by bhamadicharef** [AndyGrant/Ethereal#128]
What is typedef jmp_buf in struct Thread ?

**Comment by TerjeKir** [comment]
It's used to remember a position and jump back there.

https://www.geeksforgeeks.org/g-fact22-concept-of-setjump-and-longjump/
https://en.wikipedia.org/wiki/Setjmp.h

**Comment by bhamadicharef** [comment]
Thanks for the info. Never came across such technique in PC coding environment. Useful indeed.
