### ISSUE TITLE
Compile Msys2 Mingw64

### ISSUE THREAD

**Issue by TacticsPro** [AndyGrant/Ethereal#130]
I have tried to compile on msys2 mingw46, by downloading Ethereal master src codes, but I failed to do bash command , there is something error in makefile, I couldn't able to find!
How to compile? What is the config for makefile.sh?

**Comment by AndyGrant** [comment]
Sorry for the delayed response. The makefile requires no special work. Simply, ``make`` should work so long as ``gcc`` is on the path. Can you share the error you receive? I'm guessing you need to add make to the system path.
