### ISSUE TITLE
Ethereal Enhancement, Ethereal Playing Chess Variants, Musketeer Chess

### ISSUE THREAD

**Issue by musketeerchess** [AndyGrant/Ethereal#134]
Hi
Nice to see inspiring and open source work.

Can you please consider a fork of your engine playing chess variants.

I'm especially interested in variants i created (and naturally other popular ones). Mine is Musketeer Chess. It is discussed in many forums and also there is Musketeer Stockfish a fork of Stockfish.

Please find details here:

https://github.com/ianfab/Musketeer-Stockfish

http://talkchess.com/forum3/viewtopic.php?f=7&t=72572

https://github.com/fsmosca/musketeer-chess

i'd like to create a chess server playing chess and chess variants. The majority of the servers that exist now are based on Stockfish or LC0. It's certainly much more interesting to have servers with other engines. Please mail me to musketeerchess (a) gmail .com to discuss this and make a good development plan. I will need help in implementing and maintenance of the chess server. If you'd like to join me please let me know. If not let me know. In this case can you suggest people that can help me?

Best regards
Zied

**Comment by AndyGrant** [comment]
Zied,

I also received your email, and will be responding shortly. 

Unfortunately my web knowledge is limited. Despite the existence/success of OpenBench, I'm not qualified in any way to provide core development for a server which plays the games you request.

However, I am qualified to fork Ethereal to play chess variants. Personally it's not my primary interest, but potentially I could do a Musketeer fork. It would be an interesting chance to test the utility of my tuning setup to handle diverse gameplay. I will respond to your email in regards to this 

However, I have no interest in keeping a long maintained series of forks to play generic chess variants.

**Comment by musketeerchess** [comment]
Hi Andy

Thanks for your kind email.

Even though your fork to play chess variants isn’t maintained, as long as it works it’s not a problem.

Can you kindly refer me to someone who’s able to handle a server ?

There is already much work on Github where there are already working servers handling Stockfish. 

I think that using this work and adding your engine + Stockfish will be great.

Also I think that chess variants are the future of Chess.


Best regards


Zied

www.musketeerchess.net

**Comment by AndyGrant** [comment]
New repo for attempts to port Ethereal to Musketeer. Namely, Musketeer and any subsets of Musketeer. https://github.com/AndyGrant/Ethereal-Musketeer
