### ISSUE TITLE
Unexpected Blunder in drawn Rook endgame

### ISSUE THREAD

**Issue by TesseractA** [AndyGrant/Ethereal#138]
Ethereal had in its PV 73... Rxh3, but played 73... Rxf3?? which is a rather stark blunder by black and Forces white to recapture. Black could have played Rxh3 and drew the endgame. Not sure what caused it, but it looks like it was quickly recognized as a blunder after the forcing move was played by Stockfish.

At worst, black would have a drawn KQP v KQP endgame that would be hard to defend, but it turns out not to be so bad as to lose.

The best line goes like this: ``73... Rxh3 74. Rxh3 Kxf7 75. Rxh5 Rg3+ 76. Kb4 Kg6 77. Rh1 Kf5 78. Rb1 Ke4 79. Kc5 Rh3 ( 79... Re3 80. cxd5 cxd5 81. b4 Rh3 82. Re1+ Kd3 83. Rg1 Rh7 84. Rg8 Rc7+ 85. Kb6 Rd7 86. Rb8 Kxd4 87. Rxb7 Rxb7+ 88. Kxb7 Kxe5 89. b5 d4 90. bxa6 d3 91. a7 d2 92. a8=Q d1=Q 93. Qh8+ Kf4``

[Event "Post-CCC13 CPU Party (5|5)"]
[Site "?"]
[Date "2020.04.19"]
[Round "1"]
[White "Stockfish"]
[Black "Ethereal"]
[Result "1-0"]
[ECO "B00"]
[GameDuration "00:24:42"]
[GameEndTime "2020-04-19T02:04:06.019 PDT"]
[GameStartTime "2020-04-19T01:39:23.062 PDT"]
[Opening "KP"]
[PlyCount "199"]
[TimeControl "300+5"]
[Variation "Nimzovich defense"]

```1. e4 Nc6 2. d4 d5 3. e5 Bf5 4. Bb5 Qd7 5. Nf3 e6 6. Ba4 a6 7. Nh4 Be4 8. c3 h6 9. Be3 Nge7 10. Nd2 Bd3 11. f4 Nf5 12. Nxf5 Bxf5 13. O-O Be7 14. Rf2 Bh4 15. Rf1 Be7 16. Bc2 g6 17. Bf2 Bxc2 18. Qxc2 h5 19. Nf3 Bd8 20. a4 Ne7 21. g3 Nf5 22. h3 Be7 23. Kg2 Nh6 24. Qb3 Rb8 25. a5 Qc6 26. Rfc1 Kd7 27. Rc2 Rhg8 28. Rac1 Qb5 29. Qa2 Ke8 30. b3 Qd7 31. Rd2 Qd8 32. Rb1 g5 33. fxg5 Bxg5 34. Rd3 Nf5 35. Kh2 c6 36. Ng1 Bh6 37. Ne2 Qg5 38. Rg1 Qg6 39. Rf3 Rd8 40. c4 Bg5 41. Rf1 Rg7 42. Qa1 Kf8 43. Qd1 Kg8 44. Rg1 Qh6 45. Qd3 Qh7 46. Qc2 Nh6 47. Qxh7+ Rxh7 48. Rd1 Nf5 49. Nf4 Kf8 50. Ne2 Be7 51. Kg2 Bb4 52. Ra1 Bd2 53. Ra2 Bg5 54. Kf1 Rd7 55. Rb2 Kg7 56. Kg2 Rh8 57. Rb1 Bd2 58. Ra1 Rg8 59. Ra2 Bh6 60. Nf4 Kf8 61. Kh2 Bxf4 62. Rxf4 Rh8 63. Rd2 Rh6 64. Rc2 Ke8 65. Kg2 Rh7 66. Rc3 Rd8 67. Rcf3 Kd7 68. Kf1 Rg8 69. Ke2 Rhg7 70. Kd3 Ke8 71. Kc3 Nxg3 72. Bxg3 Rxg3 73. Rxf7 Rxf3+ 74. Rxf3 h4 75. Rf6 Rg3+ 76. Kb4 Ke7 77. Rh6 Rxh3 78. Rh7+ Kf8 79. cxd5 cxd5 80. Kc5 Kg8 81. Rh5 Kg7 82. Kd6 Kg6 83. Rh8 Kf5 84. Rh6 Rxb3 85. Rxe6 h3 86. Re8 h2 87. Rh8 b5 88. e6 Re3 89. e7 Re6+ 90. Kd7 h1=B 91. Rxh1 Re3 92. Rh6 Kg4 93. Re6 Rxe6 94. Kxe6 Kh3 95. e8=Q b4 96. Qg6 Kh2 97. Kxd5 Kh3 98. Ke4 b3 99. Kf3 b2 100. Qg3# 1-0```

**Comment by AndyGrant** [comment]
Rxf3 is preferred at first, and then replaced by h4 locally. However, much later Rxf3 is again preferred. for a brief time. My belief is that h4 is not understood well, and is considered very bad at a certain point, thus Rxf3 looks better due to the limited horizon.

A long search of Ethereal on large hardware prefers Rxh3 after many hours.
