### ISSUE TITLE
Texel turning data

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/Ethereal#146]
c-chess-cli can now generate training data (fast!), useful for supervised learning. Whether a parametric hand crafted evaluation (aka. Texel turning), or a neural network, it's exactly the same optimization problem (except perhaps that NN tend to have more weights to tune).

I think what you want is:
* position
* engine score (in cp)
* game result, from stm pov

Texel turning learns only from game results, whereas NNUE tuning flexibly combines both (custom weighted). I think we want both in the data. Of course the same Texel turning can be done purely on score cp instead of game results or mix like NNUE.

I just wonder which format is most practical.

Would a simple CSV format, like "fen,score_cp,result_stm_pov" suit ?

**Comment by AndyGrant** [comment]
All of my data just looks like [FEN] [RESULT] [?EVAL].

My latest iteration of tuning drops the CP eval, as it is no longer needed, and instead uses a purely static evaluation of the position. The caveat is that we take great care to resolve the positions we start with by applying the PVs of high-depth searches.

I think I've tried things like training the static eval to match a depth X eval. The aim being that the static eval "increases" the effective depth by more closely resembling a playout than just a static score.I was not planning on embracing NNUE until I'm forced to by virtue of dozens of engines shooting up to Ethereal-strength overnight. 

Here is/was my pipeline. How much of this can c-chess-cli cover?
Play 1M games at Hyperbullet => Randomly extract 10 positions from those games so long as they meet [X, Y, Z] criteria => Perform a depth 12 search on each of those positions and get ahold of the PV => Apply each move in the PV to get a final position => Save the final position along with the original game result.

I truly have been meaning to swap openbench to c-chess-cli, but its just not on the top of the to do list. Although I read that cutechess is going to make "radical" changes, so maybe that will force my hand.

**Comment by lucasart** [comment]
Thanks. I will implement the following:
* "fen,result_stm_pov,score_cp" (square brackets are weird, I prefer CSV, which is standard, parsing should be equally easy).
* optionally resolve positions to the end of the PV, as you describe.
* probability of saving a position specifiable (default 100%). maybe some rule50 probability adjustment formula ?

**Comment by lucasart** [comment]
It's usable now. Just slightly changed the format to
```
fen,score,result
```
So your parsing code will be changed to something like:
```
char fen[256];
int score, result;

if (sscanf(line, "%s,%d,%d\n", fen, &score, &result) < 3) {
    printf("Cannot Parse %s\n", line);
    exit(EXIT_FAILURE);
}

assert(0 <= result && result <= 2);
entries[i].result = result * 0.5;
```

**Comment by lucasart** [comment]
Implemented the PV resolution feature as well. With an extra guarantee that the recorded position cannot be in check (ie. record last position in PV that is not in check, if impossible, discard the sample).

**Comment by AndyGrant** [comment]
Hand-Crafted Evaluations are pointless at this time. So not much point in pursuing this any further. Others continue to use the datasets I had produced with this method.
