### ISSUE TITLE
(Question) Do you have linux compatible binaries?

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [AndyGrant/Ethereal#155]

**Comment by Jay-ArBrouillard** [comment]
I'd like to implement your uci engine into my discord chess ai.

**Comment by AndyGrant** [comment]
I do not provide Linux binaries. If you have a Linux machine, all you need is to clone the repo, cd into ``/src/`` and type "make".

**Comment by AndyGrant** [comment]
If you are desperate for a compile, I could do it. Truthfully I never compiled Ethereal statically on Linux -- I always tell users to compile their own, since Linux is easy as hell. However, you will get a faster compile doing it yourself.

**Comment by Jay-ArBrouillard** [comment]
Suppose I can compile it myself. It's just nice to have the entire repo as a single executable file. Thanks for the quick reply.
