### ISSUE TITLE
Compiling in OSX

### ISSUE THREAD

**Issue by fncll** [AndyGrant/Ethereal#157]
Greetings! Do you have any advice on compiling for OSX? At the moment, when I try to do so (I am running GCC 10.2.0), I get the output below and then an executable that gives the error `'./Ethereal' terminated by signal SIGSEGV (Address boundary error)`

```
gcc -O3 -std=gnu11 -Wall -Wextra -Wshadow -DNDEBUG -flto -march=native *.c pyrrhic/tbprobe.c -lpthread -lm -DUSE_POPCNT -msse3 -mpopcnt -o Ethereal
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:190,
                 from uci.c:24:
uci.c: In function 'main':
uci.c:146:13: warning: 'strncpy' output may be truncated copying 512 bytes from a string of length 8191 [-Wstringop-truncation]
  146 |             strncpy(uciGoStruct.str, str, 512);
      |             ^~~~~~~
```

thanks!

**Comment by alysson-souza** [comment]
Interesting, I never had an issue building in OSX. All I had to do is remove the '.exe' extensions from the Makefile.
I do have a fork where I'm working on adding CMake support and I know it is working there. Even from Xcode.

**Comment by AndyGrant** [comment]
Sorry, I thought I had responded to this on mobile but it appears it never went through.

Do you have a tool like valgrind or gdb to identify where the crash is actually happening? The warning you see can be safely ignored. You do have the folder of ``weights/`` right? That is required at compile time. Also, what is your CPU? Is it possible your CPU is so old that you do not have support for -mpopcnt and -msse3? (Unlikely)

If we cannot sort this out, I know there are plenty of people who have built for OSX that I can go look for.

**Comment by fncll** [comment]
I do have gdb, but no idea how to use it. My CPU is a Quad-Core Intel Core i7. I do have the weights directory...how might I move forward?

**Comment by fncll** [comment]
gdb appears problematic in Big Sur (I recently upgraded), but I read about lldb and when I use it, this is the error I see:

```
Process 1182 launched: '/Users/chris/db/chess/engines/ethereal/12.75/Ethereal-12.75/src/Ethereal' (x86_64)
Process 1182 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000010000a646 Ethereal`initMasks + 2678
Ethereal`initMasks:
->  0x10000a646 <+2678>: vpternlogq $0x55, %zmm5, %zmm5, %zmm5
    0x10000a64d <+2685>: vpor   %xmm6, %xmm1, %xmm1
    0x10000a651 <+2689>: vpor   %xmm7, %xmm2, %xmm2
    0x10000a655 <+2693>: vpand  %xmm5, %xmm1, %xmm1
Target 0: (Ethereal) stopped.
```

**Comment by fncll** [comment]
Sorry to pepper this thread, but I think I have gdb running and this is all I get when I try using it the only way I know how (then it just hangs)

```
chris@TALOSIV~/d/c/e/e/1/E/src> gdb Ethereal
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin20.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Ethereal...
(No debugging symbols found in Ethereal)
(gdb) run
Starting program: /Users/chris/Dropbox/chess/engines/ethereal/12.75/Ethereal-12.75/src/Ethereal
[New Thread 0x2103 of process 41838]
```
