### ISSUE TITLE
position of king and queen seem to have the positions swapped

### ISSUE THREAD

**Issue by calvicius** [AndyGrant/Ethereal#159]
Hello,

I'am reading your engine in order to learn your method of parallelism, and following a step by step ya have noticed that queen and king have their positions are in a wrog position (seems to me). 

I have tested with 

...
// Create the UCI-board and our threads
    threads = createThreadPool(1);
    boardFromFEN(&board, StartPosition, chess960);
for (int i=0; i<=5; i++) {
	printf("piece = %d ; ull value = %llu\n", i, board.pieces[i]);
}
...

which throws 

piece = 0 ; ull value = 71776119061282560		
piece = 1 ; ull value = 4755801206503243842
piece = 2 ; ull value = 2594073385365405732
piece = 3 ; ull value = 9295429630892703873
piece = 4 ; ull value = 576460752303423496
piece = 5 ; ull value = 1152921504606846992

and this is in binary form

0 --> 	0000000011111111000000000000000000000000000000001111111100000000
1 -->	0100001000000000000000000000000000000000000000000000000001000010
2 -->	0010010000000000000000000000000000000000000000000000000000100100
3 -->	1000000100000000000000000000000000000000000000000000000010000001
4 -->	0000100000000000000000000000000000000000000000000000000000001000
5 -->	0001000000000000000000000000000000000000000000000000000000010000

as you can see pieces 4 and 5 (queen and king, respectively) are swapped in their initial legal position

enum { PAWN, KNIGHT, BISHOP, ROOK, QUEEN, KING };

The curiosity is that board is well drawn with printBoard(Board *board)

all of this ...  is it well  designed? Because after ... , when testing king under attack, etc...

**Comment by MichaelB7** [comment]
Your question does not make any sense (seems to me ).  Enter the binary for piece 5 and it agrees to piece 5.  The fen determines the position of the pieces on the board,  not the order of  piece 0 through 5 in your table.

**Comment by calvicius** [comment]
I have looked at a little more and, now, i think the matter is understood.
the ull number is divided by 8 (eight digits per row), and then is counted from right to left in each row.

for intance for piece 5 it would be 00010000 / ..... / 00010000
the square a1 it would be the rightmost zero, and counting from right to left, then everything is OK:
- 0 -  0   - 0 -  1 - 0 -  0 - 0 - 0
h1 - g1 - f1 -e1 - d1 - c1 - b1 - a1

**Comment by AndyGrant** [comment]
![image](https://user-images.githubusercontent.com/11588594/99004867-c4b60d80-250d-11eb-9441-0fe1c4a87392.png)

This might aid you in understanding. the rightmost bit is in fact A1, not H1.

http://pages.cs.wisc.edu/~psilord/blog/data/chess-pages/rep.html
