### ISSUE TITLE
on executing null move, reset en passant square

### ISSUE THREAD

**Issue by nescitus** [AndyGrant/Ethereal#16]
and unreset it while unmaking null move.

this is likely the source of transposition table issue You mentioned on TalkChess

**Comment by AndyGrant** [comment]
I've exhausted all advice from the TalkChess thread and anything else I can think of. Still finding elo drops that cannot be explained by the added overhead (far less than a 1% slowdown). 

Any additional thoughts, before I accept the changes I've made, using zorbist keys in the correct way, despite a noticeable drop in playing strength?

**Comment by AndyGrant** [comment]
Resolved with commit af4cc7d2e554cc2e40ac1b737d7fee72e38678cd
