### ISSUE TITLE
while is searching the engine doesn't reply to 'isready'

### ISSUE THREAD

**Issue by voyag** [AndyGrant/Ethereal#177]
The uci protocol expected that the engine should reply to 'isready' even while it is searching instead ethereal reply only when the search is not launched.

**Comment by AndyGrant** [comment]
I've chosen to violate that convention of the UCI protocol, as isready would then not  _actually_ indicate that the engine isready. None of the GUIs that I have worked with have complained. One can easily remove the locks from the source code and recompile if such an issue were to arise.

**Comment by AndyGrant** [comment]
Will not resolve unless a mainstream GUI or CL application appears which uses the isready command to poll the engine during search in accordance with the specification, but in defiance of the English language.
