### ISSUE TITLE
building error on RPB4 armv8 : missing file "immintrin.h"

### ISSUE THREAD

**Issue by BrennusJ** [AndyGrant/Ethereal#178]
I'm very happy to ear news about "go nodes": thank you.

I want to test it on RaspBerry 4

So i try in many way to build it again (version 12.96) on ArmV8 (RPB4) but i get an error message of a missing file "immintrin.h" i try to understand the problem and solve it by getting this file and/or tweak makefile but i failed (and i don't understand how to enable disable the conditional NNUE eval compilation) and if it get link with the missing file error

**Comment by AndyGrant** [comment]
You need to wait until I push the code to conditionally exclude all NNUE components during the compilation. Ethereal NNNUE (and the current code on the repo) will only compile on machines with AVX2 support. 

I will push this prior to getting to v13.00. I need time to think of a cleaner solution than just using a bunch of ``#ifdef``s and making the code unreadable like most other engines.

**Comment by AndyGrant** [comment]
Tentatively resolved via https://github.com/AndyGrant/Ethereal/commit/46c23c983e8794b56b488993d489c99a365f7ddc, closing the issue barring any continued issues.
