### ISSUE TITLE
Grammatical mistake with the REAMDE.md file.

### ISSUE THREAD

**Issue by migarabhanu** [AndyGrant/Ethereal#183]
**THERE'S A TEXT WITH MISMATCH BETWEEN THE PLURALITY OF THE VERB AND THE SUBJECT UNDER THE TOPIC 'Threads' OF README.md FILE.**

The text with the mistake -

Number of threads given to Ethereal while moving. Typically the more threads the better. There is some debate as to whether using hyper-threads **provides** an elo gain. I firmly believe that for Ethereal the answer is yes, and recommend all users make use of the maximum number of threads.

**Comment by Joachim26** [comment]
Congrats!
Big bug found.

**Comment by JRattaguru** [comment]
@Joachim26 You're wrong. It's not a big bug, but needs re-correction because, there're a lot of people who use the Ethereal chess engine. 

So, please don't comment here without any knowledge.
Please maintain your discipline here !

**Comment by Joachim26** [comment]
It was certainly meant ironically...change of ONE letter in the readme, Mr. King of Programmers. The engine can even be USED without a readme.
End of comments!

**Comment by migarabhanu** [comment]
@Joachim26  a man who can't even create a repo successfully is using ironies against me. Well well !. @Joachim26  but I ask you to stop supplying jokes for developers in GitHub and be a poet with your awesome ironies...

**Comment by AndyGrant** [comment]
Ya'll are fucking weird.
