### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by SLW2K** [AndyGrant/Ethereal#185]
"boasting themselves as the only other high level NNUEs not derived from, trained on, nor duplicated from the works of the Stockfish team..." WOW! Someone has totally defeated and swept aside every other single chess engine in the world but one! Amazing!

So your engine is "second" only to Stockfish 14 (well, and Dragon 2, Lc0, and a bunch of other top engines) basically? LOL. And there's only about 30+ other powerful engines in the same rank as yours (Fire, Nemorino, Pedone, Berserk, Igel, just to name a few), literally just a few points behind. Do you really think your engine could beat Lc0 or Komodo in a tournament? You may want to get off cloud 9 before you fall off.

Shawn Weber

**Comment by AndyGrant** [comment]
The statement was accurate at the time it was made.

**Comment by SLW2K** [comment]
Sure it was, LOL.

Shawn Weber

**Comment by SLW2K** [comment]
What a fucking liar. You are a pile of shit.

Shawn Weber

**Comment by AndyGrant** [comment]
I suggest you do some more research on the topic. Particularly since your first two examples were Leela (Not NNUE), and Fire (Stockfish derivative using one of the Stockfish networks trained many months ago). Neither of which refute my claim in the past, or even now.
