### ISSUE TITLE
PONDERLOCK is locked by a thread and unlocked by another thread which is undefined behavior

### ISSUE THREAD

**Issue by voyag** [AndyGrant/Ethereal#188]
As I have written in the subject the pthread_mutex PONDERLOCK is locked by the main thread and unlocked by another thread in uciGo and this is an undefined behavior as you can read https://stackoverflow.com/questions/4608843/locking-mutex-in-one-thread-and-unlocking-it-in-the-other

**Comment by AndyGrant** [comment]
Interesting; thanks. I'll think about a solution. Although pondering is of little concern, it would be nice if it was not UB.

**Comment by AndyGrant** [comment]
Resolved by simplifying how threads are started. https://github.com/AndyGrant/Ethereal/pull/199
