### ISSUE TITLE
UCI_AnalyseMode

### ISSUE THREAD

**Issue by benini** [AndyGrant/Ethereal#189]
I think that the option "AnalysisMode" should instead be "UCI_AnalyseMode".
It is the name used by other engines, for example Stockfish, and it is indicated in the UCI protocol:
http://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by AndyGrant** [comment]
The option AnalysisMode in Ethereal is not what the protocol is referring to. I won't make the change, but I will rename it to "SyzygyFiltering" default value being true.
