### ISSUE TITLE
Ethereal for android

### ISSUE THREAD

**Issue by Alexei1981** [AndyGrant/Ethereal#19]
Hi Andy. I made my version of Ethereal-8.76 for android.For the arm7 version, I applied not only LTO, but also PGO optimization, which gave an increase in speed compared to the original by 30%! The version for arm64v8 is faster than the original arm7 version by 80% ! You can download here:
https://app.box.com/s/wp1wkv7ao0dj45yksjjkxz572a31ivhy

**Comment by AndyGrant** [comment]
I'll keep this in mind for when I do big releases in the future. Although I'm not quite sure how I would do the PGO build.

Would you mind explaining what you did to the make file in regards to -march, and how you produced the results of a PGO build.

Thanks,
Andrew
