### ISSUE TITLE
compiling error : "the clang compiler does not support '-march=native'"

### ISSUE THREAD

**Issue by BrennusJ** [AndyGrant/Ethereal#194]
Hello,

Under RPB4 aarch64 the **make** command return :

**clang: error: the clang compiler does not support '-march=native'
make: *** [makefile:109 : pgo] Erreur 1**

the result of **clang -v**

Ubuntu clang version 14.0.0-1ubuntu1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64

what it is the best way the pass this ? changing the default compiler ?

Thanks

Jérôme

**Comment by AndyGrant** [comment]
The usual reason for ``-march=native`` not being found is for Apple users who have a half-baked fork of Clang pretending to be GCC. That is not your case.

I would suggest simply going with ``make CC=gcc``, and avoid using Clang. Clang provides a nice speedup for the NNUE, but if you are compiling from the public sources, you are not getting the NNUE code anyway.
