### ISSUE TITLE
strange and surprising chess mistake : Why ?

### ISSUE THREAD

**Issue by BrennusJ** [AndyGrant/Ethereal#196]
i don't know if it is the good place to report this :
in this FEN position : 6k1/p4ppp/4q3/3p4/P4Q2/8/2r2PPP/RNB3K1 w - - 0 25

ethereal is playing white and did not see this mate in 1 against him. The move Nd2 (that need only depth analyse of 2 ply) that escape the immediate mate is not seen. With my experiment this mistake is strange even with "go nodes 500" (i will test Texel to compare for exemple). a depth analyse of 2 ply is enough to see it ?

i'm not using NNUE with "go nodes 500" that make ethereal (14.01) play around 1500 ELO

here the log (from scid) for setting and then the analyse log

Scid  : uci
Engine: id name Ethereal 14.01 (POPCNT)
Engine: id author Andrew Grant, Alayan & Laldon
Engine: option name Hash type spin default 16 min 2 max 131072
Engine: option name Threads type spin default 1 min 1 max 2048
Engine: option name EvalFile type string default <empty>
Engine: option name MultiPV type spin default 1 min 1 max 256
Engine: option name MoveOverhead type spin default 300 min 0 max 10000
Engine: option name SyzygyPath type string default <empty>
Engine: option name SyzygyProbeDepth type spin default 0 min 0 max 127
Engine: option name Ponder type check default false
Engine: option name AnalysisMode type check default false
Engine: option name UCI_Chess960 type check default false
Engine: info string licensed to Unlicensed
Engine: uciok
Scid  : isready
Engine: readyok
Scid  : setoption name Hash value 512
Scid  : isready
Engine: info string set Hash to 512MB
Engine: readyok
Scid  : setoption name Threads value 4
Scid  : isready
Engine: info string set Threads to 4
Engine: readyok
Scid  : setoption name MultiPV value 3
Scid  : isready
Engine: info string set MultiPV to 3
Engine: readyok
Scid  : setoption name Ponder value false
Scid  : isready
Engine: readyok
Scid  : setoption name EvalFile value <empty>
Scid  : isready
Engine: info string set EvalFile to <empty>
Engine: readyok
Scid  : setoption name MoveOverhead value 300
Scid  : isready
Engine: info string set MoveOverhead to 300
Engine: readyok
Scid  : setoption name SyzygyPath value <empty>
Scid  : isready
Engine: info string set SyzygyPath to <empty>
Engine: readyok
Scid  : setoption name SyzygyProbeDepth value 0
Scid  : isready
Engine: info string set SyzygyProbeDepth to 0
Engine: readyok
Scid  : setoption name AnalysisMode value false
Scid  : isready
Engine: readyok

Scid  : position startpos moves d2d4 d7d5 c2c4 g8f6 c4d5 f6d5 e2e4 e7e6 e4d5 e6d5 g1f3 f8e7 f1d3 b7b6 e1g1 c8a6 d3a6 b8a6 d1d3 d8c8 f1e1 c7c5 d3e3 c8d7 e3d3 a6c7 d4c5 b6c5 b2b4 e8g8 d3e3 f8e8 b4c5 e7c5 e3c5 e8e1 f3e1 d7e6 c5a5 c7b5 a2a4 b5d4 a5b4 d4c2 e1c2 a8c8 b4f4 c8c2
Scid  : go nodes 500
Engine: info depth 1 seldepth 1 multipv 1 score cp 705 time 1 nodes 88 nps 44000 tbhits 0 hashfull 0 pv h2h3 
Engine: info depth 1 seldepth 1 multipv 2 score cp 638 time 2 nodes 182 nps 60000 tbhits 0 hashfull 0 pv a4a5 
Engine: info depth 1 seldepth 1 multipv 3 score cp 465 time 2 nodes 198 nps 66000 tbhits 0 hashfull 0 pv g1f1 
Engine: info depth 2 seldepth 2 multipv 1 score cp 714 time 2 nodes 279 nps 93000 tbhits 0 hashfull 0 pv h2h3 d5d4 
Engine: info depth 2 seldepth 2 multipv 2 score cp 638 time 2 nodes 281 nps 93000 tbhits 0 hashfull 0 pv a4a5 d5d4 
Engine: info depth 2 seldepth 2 multipv 3 score cp 321 time 2 nodes 281 nps 93000 tbhits 0 hashfull 0 pv g1f1 d5d4 
Engine: info depth 3 seldepth 3 multipv 1 score cp 713 time 2 nodes 386 nps 128000 tbhits 0 hashfull 0 pv a1a3 d5d4 h2h3 
Engine: info depth 3 seldepth 3 multipv 2 score cp 638 time 2 nodes 396 nps 132000 tbhits 0 hashfull 0 pv a4a5 d5d4 a5a6 
Engine: info depth 3 seldepth 3 multipv 3 score cp 599 time 2 nodes 405 nps 135000 tbhits 0 hashfull 0 pv h2h3 d5d4 h3h4 
Engine: bestmove a1a3 ponder d5d4
Scid  : stop

What to think about this ?

**Comment by AndyGrant** [comment]
Nothing tricky here, this is what happens when node counts are extremely low. Moves at the root get pruned and ignored completely at the lowest depths. It takes Ethereal (non-NNUE) 17ms to identify that Nd2 is the only reasonable move
