### ISSUE TITLE
Normalized evaluation

### ISSUE THREAD

**Issue by dav1312** [AndyGrant/Ethereal#198]
Ethereal's evaluations seem pretty high compared to other top engines, implement Stockfish's normalized evaluation, having a +1.00 be a 50% win.

https://github.com/vondele/WLD_model

**Comment by AndyGrant** [comment]
I've never been huge on this because displaying the adjusted evaluation is an artificial effort that masques the engines actual (lack-of) understanding, similar to lowering the eval as the fifty move rule approaches. 

If you can tell me what KIND of PGNs they used for this model, then I will try to generate my own and see what it looks like. Namely, what was the time control of the games, from what opening book were they selected, what if any adjudications were used during gameplay.

**Comment by ghost** [comment]
Stockfish's normalized evaluation isn't always +1.00 representing a 50% win rate. It is only +1.00 representing a 50% win rate at move 32. There is an roughly linearly increasing trend in the evaluation for the 50% win rate in Stockfish as the move increases, ranging from +0.94 at move 10 to +1.25 at move 120. And then this is just for the static evaluation iirc, search throws everything off; i.e. it is likely that if the position is winning, what was once +1.00 for static evaluation would increase past +1.00 as the engine spends time searching the game tree. 

In my opinion, if Andrew Grant really wants to use WLD it would probably be better to directly train a neural network which outputs WLD percentages like Winter and Leela. 

Incidentally I created an issue on the exact topic a few days ago, and then closed the issue as I discovered that things aren't as simple as it may seem at first glance. 

https://github.com/AndyGrant/Ethereal/issues/197

Although, there are a few engines that do need normalization, especially Igel and Minic. I do not consider Ethereal to be one of those engines.

**Comment by AndyGrant** [comment]
Unfortunately there is virtually a zero percent chance I generate WDL networks explicitly. I simply don't have the time for it -- my training back log is massive. I'm missing out on free elo, in need of a trainer rewrite.

**Comment by dav1312** [comment]
> If you can tell me what KIND of PGNs they used for this model, then I will try to generate my own and see what it looks like. Namely, what was the time control of the games, from what opening book were they selected, what if any adjudications were used during gameplay.

Standard Fishtest LTC games afaik
60+0.6
UHO_XXL_+0.90_+1.19
`-resign movecount=3 score=600 -draw movenumber=34 movecount=8 score=20`

_Note that the model according to Vondele is very little dependent on TC conditions_

**Comment by AndyGrant** [comment]
https://github.com/AndyGrant/Ethereal/commit/73e12e2b82e52de7b4b3221cc079829270d38fbb
