### ISSUE TITLE
Resolve returning -Mate scores when allocated time has elapsed

### ISSUE THREAD

**Issue by AndyGrant** [AndyGrant/Ethereal#2]
As of now, the method of leaving the search routines due to the final allocated time margin being passed will return -Mate scores. This is annoying, and problematic.

**Comment by Mk-Chan** [comment]
It doesn't seem like you're using that return value anywhere, just printing it as part of the UCI output

**Comment by AndyGrant** [comment]
I worry that the -Mate scores have an unnoticed affect on the scoring of the root moves.

I noticed an issue while watching Ethereal7.78 play it's gauntlet for CCRL, in which one move, call it A, was clearly worth +4 (or more. Confirmed by StockFish). However, when it came time to print the best move, it instead picked move B, worth +0. Ethereal's opponent immediately jumped from -4.00 evals positive evals.

However, the reason for creating this issue, was simply to remind myself to find a better way to exit the search. It's annoying to see -Mate reported as a score. It also affects DrawThreshholds / ResignThreshholds.

**Comment by Mk-Chan** [comment]
You could do it the way I do it in my program in the iterative deepening:
till desired depth
1.         conduct search
2.         if time is up, break loop
3.         store best move in a local var

return locally stored best move.

this way you always return the best move of the most recently completed iteration

**Comment by AndyGrant** [comment]
Still throwing back the -MATE scores, but no longer printing them. After careful consideration, the -MATE scores do not have any unintended actions. 

Resolved with commit e184a1e0c09b0720164c8eb246c82ab9ce1fa218
