### ISSUE TITLE
syzygy

### ISSUE THREAD

**Issue by Alexei1981** [AndyGrant/Ethereal#20]
Hi Andy. Are you going to do support in syzygy in Ethereal?

**Comment by AndyGrant** [comment]
It is something I would like to do, but it is not worth any elo so I've been putting it off.

**Comment by Alexei1981** [comment]
Ok 'Thanks for the engine. I still have not seen such rapid progress in the Elo.

**Comment by AndyGrant** [comment]
Resolved in https://github.com/AndyGrant/Ethereal/commit/4fe46d41a1ff1204835a4a8f62986815a35516e2
