### ISSUE TITLE
tt_store comment confusion

### ISSUE THREAD

**Issue by mcthouacbb** [AndyGrant/Ethereal#202]
On [line 140 of transposition.c](https://github.com/AndyGrant/Ethereal/blob/master/src/transposition.c#L140), the comment says the formula for finding the replacement is `MAX(x1, x2, x3)` where xN is equal to `depth - 4 * ageDiff`.
However, the code directly below it seems to be finding the slot with `MIN(x1, x2, x3)`, and not `MAX(x1, x2, x3)`.

**Comment by AndyGrant** [comment]
You are correct.

**Comment by mcthouacbb** [comment]
Fixed in 517d7aa
