### ISSUE TITLE
queen contribution to attackedBy2 is wrong

### ISSUE THREAD

**Issue by TomHyer** [AndyGrant/Ethereal#210]
https://github.com/AndyGrant/Ethereal/blob/fdfc70b65cc0d98632f4f102c462cdb9f6ded952/src/evaluate.c#L830

should read

attacks = rookAttacks(sq, ei->occupiedMinusRooks[US]) | bishopAttacks(sq, ei->occupiedMinusBishops[US]);

**Comment by dsjoerg** [comment]
At first I didn't understand why your proposal was correct but I get it now.

For rooks and bishops, we include see-through attacks for computing attackedBy2.
For example for rooks: https://github.com/AndyGrant/Ethereal/blob/fdfc70b65cc0d98632f4f102c462cdb9f6ded952/src/evaluate.c#L771

I guess for extra correctness we could remove queens as well.

If that makes sense to you I'll submit a PR, why not 😃

**Comment by AndyGrant** [comment]
This might be something that I knew at the time, and rejected from some testing. Here is a test that was run in 2018 http://chess.grantnet.us/test/1666/ . In the base version of this test, we had the behavior you were looking for. This implies to me that I removed it later, either as a simplification, or as a gainer. Although I can't find the test readily, I'm sure the git blame could with enough fighting.

**Comment by AndyGrant** [comment]
Ah! Here is the commit https://github.com/AndyGrant/Ethereal/commit/4c3f29614859f989c5e1f2ce57ef3a89969ed72a

So while your change is sensible for the rest, it looks like it would be a very bad idea. At least at the time, and in the context of the rest of the evaluation.

The test links do not work, unfortunately. The endpoint should be /test/<id>, but correcting that gets you to weird things. Its likely that when I merged grantnet with koivisto-group, this happened.

**Comment by AndyGrant** [comment]
HCE certainly brings back memories. Ethereal was ahead of the times with the HCE-Tuner, which made development of the evaluation very fast paced compared to the rest of the field at the time. Very likely the sole determinant in why Ethereal was able to shoot up to #3 below Stockfish & Komodo (& the clones I left out)

**Comment by TomHyer** [comment]
Is that because of the dual use of the calculated ‘attacks’?

*	For determining attackedBy2 (correctness issue)
*	For evaluation per se (interacts unpredictably with eval weights)

**Comment by AndyGrant** [comment]
The definition of attackedBy2 is entirely subjective. And as a result, its definition flows directly from whatever brings the most elo. 

You could equally argue that the Bishop and Rook contributions are the wrong ones, as they allow x-ray support, and that in fact the Queen attack contribution is the only correct one of the three.
