### ISSUE TITLE
Bug in evaluateComplexity

### ISSUE THREAD

**Issue by Oscar-Gavira** [AndyGrant/Ethereal#213]
int evaluateComplexity(EvalInfo *ei, Board *board, int eval)
{
...
    // Compute the initiative bonus or malus for the attacking side
    complexity =  ComplexityTotalPawns  * popcount(board->pieces[PAWN])
               +  ComplexityPawnFlanks  * pawnsOnBothFlanks
               +  ComplexityPawnEndgame * !(knights | bishops | rooks | queens)
               +  ComplexityAdjustment;
...
// Create a MakeScore int of complexity to make use of ScoreEG
*    int v = sign * MAX(ScoreEG(complexity), -abs(eg)); /* ScoreEG(complexity) - It is incorrec. Always returns zero. */

    if (TRACE) T.eval       = eval;
    if (TRACE) T.complexity = complexity;
    return MakeScore(0, v);
}

**Comment by AndyGrant** [comment]
You'll need to provide more information, and perhaps format the code so it is more clear what you are trying to convey.

I do not believe ScoreEG(complexity) will always return 0. It might always return 0 for the MG, due to the nature of the values, however. But that is not how we use it.

```
const int ComplexityTotalPawns  = S(   0,   8); <-- 0 MG, 8 EG
const int ComplexityPawnFlanks  = S(   0,  82);
const int ComplexityPawnEndgame = S(   0,  76);
const int ComplexityAdjustment  = S(   0,-157);
```

**Comment by Oscar-Gavira** [comment]
Sorry. All good.
