### ISSUE TITLE
Random vs random vs random

### ISSUE THREAD

**Issue by CMCanavessi** [AndyGrant/Ethereal#29]
I made an experiment and matched "EtherealTrueRandom" vs "Teki Random Mover" (see https://github.com/Mk-Chan/Teki/tree/v0.1) and expected them to be very evenly matched, they are both random movers after all. Instead, I got the following:

Score of EtherealTrueRandom (8.97) vs Teki: 1265 - 638 - 8097  [0.531] 10000
Elo difference: 21.81 +/- 2.95
Finished match

So, as per your advice, I contacted Manik and asked him to look at your code and compare it to Ethereal. Here's what he has to say:

> It seems Andrew is using movelist[rand() % size] to get a random move. The problem is that this is not truly random. My random function uses c++11s standard library uniform integer random distribution which has been shown to be much closer to a real uniformly random distribution. Source: https://channel9.msdn.com/Events/GoingNative/2013/rand-Considered-Harmful
> 
> Technical explanation:
> Because size is not always a multiple of the range of rand() [which by itself is a bad rng by virtue of being linear congruential in glibc], rand() % size does not resolve to an integral number of sets of [0, size). The last set(for the [RANDMAX - size + 1, RANDMAX] will have less of a range and thus reduced randomness. This slightly favors moves in the earlier part of the movelist, which, judging by ethereal random's movegen are pawn moves. My suspicion is that ethereal moves pawns and queens a lot more than Teki.
> 
> Regards,
> Manik

I also made another experiment, I matched EtherealTrueRandom against itself for 100k games and looked at the ECO openings distribution, here's the result:

> Games   = 100000   ( no result = 0,  FEN tags = 0 )
> Players = 1   ( clusters = 1 )
> Date Range: 2018.03.09 - 2018.03.09
> 
> Games with:  WhiteElo = 0   BlackElo = 0   BothElos = 0
> 
> White Wins = 7789 ( 7.79 % )
> Draws      = 84413 ( 84.41 % )
> Black Wins = 7798 ( 7.8 % )
> White Pct = 50.0 %
> Black Pct = 50.0 %
> 
> ECO:  Total = 100000  A: 94732  B: 4477  C: 504  D: 287  E: 0
> PlyCount:  Total = 100000  Range: 4-865  Average = 340.21  StdDev = 112.12
> 
> finished: be sure to rename/copy outSummary
> 

There's very little variation. Then I did the same with Teki and there's little variation too, but it's a bit better:

> Games   = 100000   ( no result = 0,  FEN tags = 0 )
> Players = 1   ( clusters = 1 )
> Date Range: 2018.03.09 - 2018.03.09
> 
> Games with:  WhiteElo = 0   BlackElo = 0   BothElos = 0
> 
> White Wins = 8973 ( 8.97 % )
> Draws      = 82274 ( 82.27 % )
> Black Wins = 8753 ( 8.75 % )
> White Pct = 50.11 %
> Black Pct = 49.89 %
> 
> ECO:  Total = 100000  A: 90834  B: 781  C: 4178  D: 4207  E: 0
> PlyCount:  Total = 100000  Range: 6-901  Average = 357.18  StdDev = 154.9
> 
> finished: be sure to rename/copy outSummary
> 

I don't know if you're using random generation for anything in the "real" version of Ethereal, but if you are, maybe this will help you make it better :)

**Comment by CMCanavessi** [comment]
The new rand64 version scores exactly the same as the old one:

> Score of TrueEtherRand vs EtherTrueRand_new: 793 - 793 - 8414  [0.500] 10000
> Elo difference: 0.00 +/- 2.71
> Finished match

**Comment by Mk-Chan** [comment]
Well I'm flummoxed, I ran a simple C++ program that runs both our RNGs for a billion values and that gives a pretty even distribution for rand(), Andy's rand64() [seeded the same way he did] and C++11's random library. So that test clearly failed.

The only other thing I could think of is you didn't play enough games because it's logically impossible for random movers to be so far apart.

**Comment by AndyGrant** [comment]
Is is possible Teki was making illegal moves or losing on time? 10,000 games with that kind of confidence internal... I would be AMAZED if that was just statistical noise.

Some people encode Promotions as one move, some as four. If you encode as one then maybe that is the issue?

I'm not hell bent on finding the difference, but I am very confused.

**Comment by AndyGrant** [comment]
My last thought ... and this seems like It really cannot be true -- Do the probabilities change because you are generating psuedo legal moves instead of legal ones?

**Comment by Mk-Chan** [comment]
No I have 4 separate moves for promotions and while I do generate pseudo-legal moves, I remove any encountered illegal move in case I'm unable to make the move and regenerate a random number so I don't think it should have an effect.

It is possible that Teki is losing on time or making illegal moves. Could you check the PGN @CMCanavessi ?

**Comment by CMCanavessi** [comment]
Losing on time definitely not, because the games are played at TC=infinite. They are very fast anyways, as both engines are instant movers.

I checked the pgn for the word "illegal" and found nothing. Anyways, I have attached the pgn so you can check it if you want. If you have any problems extracting the pgn file, rename it to .7z (as it didn't let me attach 7z files, i just renamed it to .zip).

Mind you, this is the previous Ethereal Random version, the one with rand() and not rand64(), and 10.000 games. I can make a new match of 100.000 games with the new rand64 version vs teki again if needed, will take a couple of hours.

[TestRandom.zip](https://github.com/AndyGrant/Ethereal/files/1798656/TestRandom.zip)

**Comment by Mk-Chan** [comment]
Hmm... No illegal, no forfeit. This is really just weird. How about any other random movers?

**Comment by CMCanavessi** [comment]
Well, it's not easy to find them. The POS engines can make random moves, but they need to be executed with --brain-mode random (or something like that), which I couldn't make it work in cutechess (using arg="--brain-mode random" does not seem to work).
Brutus RND is another one, but it crashes in my pc. Maybe it's related to my ryzen processor.
And Randscacs doesn't move instantly, so it takes longer to test it.

**Comment by CMCanavessi** [comment]
Wait, I just realized that the zip I attached earlier was the one with Ethereal old vs Ethereal new. It seems I deleted the old pgn I did with Ethereal old vs Teki.

I have started a new match with Ethereal new vs Teki, 100.000 games. Should be done in a couple of hours.

From what I'm seeing, it's already starting to show the same behaviour.

**Comment by CMCanavessi** [comment]
![imagen](https://user-images.githubusercontent.com/34553661/37234606-95fb082c-23d7-11e8-8c50-1f6e2e7598cc.png)

You can already see the trend, it's exactly the same as before

**Comment by CMCanavessi** [comment]
![imagen](https://user-images.githubusercontent.com/34553661/37234870-16db449c-23d9-11e8-8708-f7f75ef330d4.png)

**Comment by CMCanavessi** [comment]
I stopped as it was exactly the same result as before, but got an idea that, as I was playing the matches without opening book, then maybe Ethereal had better opening knowledge (besides random) so I made a new test, using 8-move opening book and playing reverse games. The results are identical:

Score of Ethereal True Random rand64 vs Teki Random Mover: 1249 - 652 - 8099  [0.530] 10000
Elo difference: 20.77 +/- 2.95
Finished match

**Comment by CMCanavessi** [comment]
[games.zip](https://github.com/AndyGrant/Ethereal/files/1798815/games.zip)

**Comment by Mk-Chan** [comment]
I have one idea but it's probably stupid. Lemme arrange teki's movegen to match the order of ethereal's I'll try that out and do some matches

**Comment by Mk-Chan** [comment]
This is hilarious.
Changing the move ordering seemed to be the solution. Take a look at this:
```
I changed the move generation order from:
piece captures, pawn captures, quiet promotions, castling, piece quiets, pawn quiets
to:
quiet promotions, pawn captures, pawn quiets, piece captures, piece quiets, castling

and got:
Score of EtherTrueRand 9.21 vs Teki: 981 - 723 - 8296  [0.513] 10000
Elo difference: 8.97 +/- 2.80
Finished match
```

It seems the random number gods are at work with varying movelist size and random number generators. No doubt that different move ordering will further change the result.

**Comment by AndyGrant** [comment]
Since that seemed to have an affect. Can you do legal move generation instead, and then pick from that list. Instead of picking from the psuedoes until you get a legal.

I feel like that changes things.

**Comment by Mk-Chan** [comment]
I agree now, it really might make a difference! But it seems very counter-intuitive to me still. I'll just try it

**Comment by Mk-Chan** [comment]
Legal movegen Teki:
```
Score of EtherTrueRand 9.21 vs Teki: 882 - 794 - 8324  [0.504] 10000
Elo difference: 3.06 +/- 2.78
```
You're right, but it still baffles me how this makes a difference

**Comment by AndyGrant** [comment]
So here is my thought. Take a look at a pinned queen. This queen likely only has a few legal moves, but has a large list of illegal ones. So if our random number falls within the queen list, we will likely have to generate a new one. For some reason (im postulating) the RNG is less likely to produce another number which sits in the queens list, thus making it more likely to move a lower valued piece. 

I would venture to guess that having a mobile queen in random games is what wins things. If the queen is out, you have many more capture possibilities. And for random games all we can really do is hope to take enough material to stumble upon a mate.

Right or wrong, still extremely un-intuitive. Thanks for taking the time to investigate here. I think I'll close this now.

@CMCanavessi If you want a version of Ethereal which matches they way Teki does things, I can do that for you.

**Comment by Mk-Chan** [comment]
We can finally bury the beaten horse:

https://github.com/Mk-Chan/Teki/blob/master/src/utils.h#L54

Reseeding the RNG everytime with the same value every millisecond => same index picked from the movelist. After removing an illegal move, it just picks the next move (which is further along the movelist and definitely not random).

That reasonably explains the weird behaviour.

Found by @kz04px on ##chessprogramming irc.

**Comment by Safrad** [comment]
> Well, it's not easy to find them. The POS engines can make random moves, but they need to be executed with --brain-mode random (or something like that), which I couldn't make it work in cutechess (using arg="--brain-mode random" does not seem to work).
> Brutus RND is another one, but it crashes in my pc. Maybe it's related to my ryzen processor.
> And Randscacs doesn't move instantly, so it takes longer to test it.

I have created another instant random mover engine: https://sx.rosada.cz/projects/sxrandom
Brutus RND crashes also on Intel CPU.
