### ISSUE TITLE
perft segfaults

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/Ethereal#49]
I was trying to run your perft.py script, to do some speed measures on #47. But it crashed. So I tried master, it also crashed. Here's the minimal reproduction with master:
```
ucinewgame
position fen 1r1qk2r/5ppp/Q2p4/6R1/4P1bq/2N5/P1P5/4K1N1 b k - 0 23
print
  |---|---|---|---|---|---|---|---|
8 | . | r | . | q | k | . | . | r |
  |---|---|---|---|---|---|---|---|
7 | . | . | . | . | . | p | p | p |
  |---|---|---|---|---|---|---|---|
6 | Q | . | . | p | . | . | . | . |
  |---|---|---|---|---|---|---|---|
5 | . | . | . | . | . | . | R | . |
  |---|---|---|---|---|---|---|---|
4 | . | . | . | . | P | . | b | q |
  |---|---|---|---|---|---|---|---|
3 | . | . | N | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
2 | P | . | P | . | . | . | . | . |
  |---|---|---|---|---|---|---|---|
1 | . | . | . | . | K | . | N | . |
  |---|---|---|---|---|---|---|---|
    A   B   C   D   E   F   G   H
fen: 1r1qk2r/5ppp/Q2p4/6R1/4P1bq/2N5/P1P5/4K1N1 b k - 0
perft 1
Segmentation fault (core dumped)
```

**Comment by lucasart** [comment]
I think your FEN is wrong in `perft.epd`. This FEN also crashes Demolito. But I'm looking at this FEN, and I can't see why...

**Comment by lucasart** [comment]
Ah, It's obvious! It cannot be black's turn to play, because Qh4 captures Ke1. Wrong FEN. Need to correct `perft.epd`.

**Comment by AndyGrant** [comment]
Removing the last few positions -- verified the rest through Stockfish. Does not crash on windows, but that tends to be the case with a lot of illegal operations. SF also does not crash on windows. Probably comes down to a piece lookup using getlsb(0), an illegal memory lookup follows, and windows is okay with that sometimes.

**Comment by AndyGrant** [comment]
Resolve with https://github.com/AndyGrant/Ethereal/commit/bdbad8a3e80d826d11ff4e111f7bdcb9cc715066
