### ISSUE TITLE
Evaluate draws

### ISSUE THREAD

**Issue by ratosh** [AndyGrant/Ethereal#62]
Using several function instead of popcount should give a small speed improvement.

**Comment by AndyGrant** [comment]
You are correct. Also, you got me looking at evaluteDraws(). I release that insufficient material should be done in the search, not in the eval ... which led me to notice I accidentally disabled the fifty move rule recently, although it showed no elo loss.

**Comment by ratosh** [comment]
I think there is another really small speed improvement in draw detection:
 `for (int i = board->numMoves - 2; i >= 0; i -= 2) {`
Can it be:
 `for (int i = board->numMoves - 4; i >= 0; i -= 2) {`
If i'm not wrong you should need at least 4 plies to repeat the current move.

Also can the draw detection be done after making a move on search? It should avoid redoing some draw detection (when it is not dropped by lmr or something).

**Comment by AndyGrant** [comment]
Draw detection is not tried until the move is to actually be searched.

As for the minus 4, this will not work. I could come up with an example, but the -4 makes sense if you were to move back and forth, ie the typical human draw by repetition. But really, we care if the position has been repeated at all in the last < 50 moves.

**Comment by ratosh** [comment]
You do a draw evaluation on LMR search and if it holds you do another search that would do another draw evaluation, right?

The move repetition window should be (inside the 50 move repetition) and the fastest way to draw should be the typical human draw by repetition so you should not be able to repeat the current board before 4 plies (board->numMoves- 4).

**Comment by AndyGrant** [comment]
Okay -- I see the case for LMR. I'll measure it, but it will make things a bit nasty.

I see what you are saying about -4 now, but I still think there is the case of the position being the same, as a result of a null move being made.

**Comment by ratosh** [comment]
I think only 2 null moves in a row would give you the same board in 2 plies.

**Comment by AndyGrant** [comment]
Okay. You are right about this.

However, I don't think I want to do it, just in the off chance that I at some point allow a double null move.  This is one of those subtle things that I will forget about.

I am doing your evaluateDraw() suggestion, as well as the fixes to some various things. Testing looks like a good non-regression. http://chess.grantnet.us/viewTest/1391/

**Comment by ratosh** [comment]
Great! Really small improvement, but still a improvement.

**Comment by AndyGrant** [comment]
Resolved https://github.com/AndyGrant/Ethereal/commit/d9171caf02ce01b34b2a79fc5aefc14b17f82495
