### ISSUE TITLE
Ethereal 11.11 loosing its thinking time

### ISSUE THREAD

**Issue by gpaunica** [AndyGrant/Ethereal#80]
Hello Mr.,
I found Ethereal 11.11 on the internet, and when I create an engine match with time control 40 Moves in 30 Minutes reapiting, for first 40 moves Ethereal doesn't have this problem, but in second intermediar time (moves from 41 to 80) I saw that Ethereal remains with less than 10 seconds for I think 14 or 15 moves.
This situation happened more than once.
Thanks.

**Comment by AndyGrant** [comment]
There is no way to convey the initial time vs the second set, third set, ... in the UCI specification. So if you are seeing weird time things they are intended, and able to happen during any 40move sequence.

**Comment by gpaunica** [comment]
Thanks for your answer Mr.,
So, when I setup as time control a number of moves in "n" minutes you are sugesting to add increament for "n" minutes? 40 moves in 20 Minutes + 5 Seconds/move for example? It shouldn't be any problem with increamental time control, right?
Thanks.
