### ISSUE TITLE
Margins for SEE pruning

### ISSUE THREAD

**Issue by Matthies** [AndyGrant/Ethereal#85]
No real issue but maybe worth to investigate:

I compared the see pruning margings that are used for quiet and tacticle moves in different engines (to get an idea what is worth testing in my engine):

Laser:
 - quiet: 	-24 * pruneDepth * pruneDepth
 - tacticle:	-100 * depth

SF:
 - quiet: 	-29 * lmrDepth * lmrDepth
 - tacticle:	-PawnValueEg * depth

Ethereal:
 - quiet: 	-80 * depth
 - tacticle:	-18 * depth * depth

Xiphos:
 - quiet: 	-15 * _sqr(depth - 1)
 - tacticle:	-100 * depth

Yours is the only that uses squared depth for tacticle moves instead of quiet moves. Have you tested the other way round?

**Comment by AndyGrant** [comment]
You can see everything I have tried by going to http://chess.grantnet.us/search/ and searching the keyword "SEE". I am looking through this now.

I believe I have tried a linear approach to the tactical pruning margins. 

I have tried, and not found much success with the quadratic approach for quiets, but this would have been quite some time ago.

**Comment by AndyGrant** [comment]
* http://chess.grantnet.us/viewTest/3387/ using Tactical = 80 * depth
* http://chess.grantnet.us/viewTest/3388/ using Tactical = 120 * depth

May investigate playing with the quiet margins as well, once my CPUs finish the above.

**Comment by AndyGrant** [comment]
I'm open to testing any other variants, but for now I'm going to close this. Thanks for the suggestion.

**Comment by Matthies** [comment]
Okay, bad luck. I wasn't successful with pruning quiet moves with bad see at all.
