### ISSUE TITLE
Ethereal kind of stops in some position

### ISSUE THREAD

**Issue by Matthies** [AndyGrant/Ethereal#86]
Hi.

Have a look at this:

uci
id name Ethereal 11.53
id author Andrew Grant & Laldon
option name Hash type spin default 16 min 1 max 65536
option name Threads type spin default 1 min 1 max 2048
option name MoveOverhead type spin default 100 min 0 max 10000
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 0 min 0 max 127
option name Ponder type check default false
option name UCI_Chess960 type check default false
uciok
position fen 8/8/8/4B3/8/2N2K2/8/6k1 w - - 22 12
go depth 30
info depth 1 seldepth 1 score cp 900 time 0 nodes 6 nps 6000 tbhits 0 hashfull 0 pv f3f4
info depth 2 seldepth 2 score cp 915 time 0 nodes 25 nps 25000 tbhits 0 hashfull 0 pv f3e4 g1g2
info depth 3 seldepth 3 score cp 893 time 0 nodes 77 nps 77000 tbhits 0 hashfull 0 pv f3g3 g1f1 g3f4
info depth 4 seldepth 4 score cp 898 time 0 nodes 112 nps 112000 tbhits 0 hashfull 0 pv f3g3 g1f1 g3f4 f1g2
info depth 5 seldepth 6 score cp 901 time 0 nodes 357 nps 357000 tbhits 0 hashfull 0 pv f3e4 g1f1 e4d4 f1f2 d4d5
info depth 6 seldepth 7 score cp 949 time 0 nodes 952 nps 952000 tbhits 0 hashfull 0 pv f3e4 g1h1 e4d4 h1g1 c3d5 g1g2
info depth 7 seldepth 8 score cp 983 time 16 nodes 2525 nps 148000 tbhits 0 hashfull 0 pv e5g3 g1h1 c3d1 h1g1 d1e3 g1h1 f3e4
info depth 8 seldepth 11 score cp 959 time 16 nodes 3588 nps 211000 tbhits 0 hashfull 0 pv e5g3 g1h1 c3d1 h1g1 d1f2 g1f1 f2e4 f1g1
info depth 9 seldepth 10 score cp 994 time 16 nodes 5529 nps 325000 tbhits 0 hashfull 1 pv c3d1 g1f1 d1e3 f1g1 e5b8 g1h1 f3g3 h1g1 b8f4 g1h1
info depth 10 seldepth 13 score cp 976 time 31 nodes 12238 nps 382000 tbhits 0 hashfull 3 pv c3d1 g1f1 d1e3 f1g1 e5f4 g1h1 f3e2 h1g1 f4b8 g1h1 b8c7
info depth 11 seldepth 16 score cp 983 time 31 nodes 20418 nps 638000 tbhits 0 hashfull 3 pv c3d1 g1f1 d1e3 f1g1 e5f4 g1h1 f3e2 h1g1 f4b8 g1h1 e2e1 h1g1 b8f4 g1h1
info depth 12 seldepth 18 score cp 970 time 47 nodes 36195 nps 754000 tbhits 0 hashfull 5 pv e5g3 g1f1 c3d1 f1g1 d1e3 g1h1 f3e4 h1g1 e4f4 g1h1 f4f3 h1g1 f3e2 g1h1 e2f1
info depth 13 seldepth 23 score cp 967 time 62 nodes 56402 nps 895000 tbhits 0 hashfull 8 pv e5g3 g1f1 c3d1 f1g1 d1e3 g1h1 f3e4 h1g1 e4f4 g1h1 f4f3 h1g1 f3e2 g1h1 e2d3 h1g1 d3e4 g1h1 e4d5 h1g1 d5e6
info depth 14 seldepth 22 score cp 975 time 94 nodes 92657 nps 975000 tbhits 0 hashfull 13 pv e5g3 g1f1 c3d1 f1g1 d1e3 g1h1 g3f2 h1h2 e3d5 h2h3 d5f4 h3h2 f3e4 h2h1 e4d5 h1h2 d5e6 h2h1 f2a7 h1h2
info depth 15 seldepth 24 score cp 993 time 141 nodes 160610 nps 1131000 tbhits 0 hashfull 20 pv e5g3 g1f1 c3d1 f1g1 d1e3 g1h1 g3f2 h1h2 e3d5 h2h3 d5f4 h3h2 f3e4 h2h1 e4d5 h1h2 d5e6 h2h1 e6f7 h1h2 f7g7 h2h1 f2a7
info depth 16 seldepth 32 score cp 981 time 359 nodes 455951 nps 1266000 tbhits 0 hashfull 53 pv e5g3 g1f1 c3d1 f1g1 d1e3 g1h1 g3f2 h1h2 e3d5 h2h3 d5f4 h3h2 f3e4 h2h1 e4d5 h1h2 d5e6 h2h1 e6f7 h1h2 f7e7 h2h1 e7d6 h1h2 d6c7 h2h1 c7d7 h1h2

Then... nothing. Output just stops at depth 16. Ethereal process still at max cpu but it seems stuck. Same with go infinite.

**Comment by AndyGrant** [comment]
I took both V11.53, and current master (V11.57), and I was able to produce the same "stopping" behavior. 

If I execute a ``go movetime <x>`` search, the process will eventually return a bestmove when ``<x>`` has expired, so Ethereal is not freezing, or crashing, or whatever else.

Most likely, and I'll allow the process to run for quite some time to perhaps demonstrate this, Ethereal has decided that the "expected" line of play from the depth 16 search is actually very very bad, and thus is coming up with an entirely new line of play, but starting with depth 17. That would take a very long time to do. There is a good reason why engines work from depth 1 -> N.

Also, after having looked at the actual position, its possible that Ethereal is either JUST about to resolve the position to a mate (could take some time since it was suddenly found, when no progress had been made otherwise), or Ethereal is now seeing that the position is drawn (perhaps correctly or incorrectly)

You can help me test as well -- repeat the position and inputs you did before, but just give Ethereal a few minutes, to see if any information starts to be reported.

**Comment by Matthies** [comment]
Testing with 11.57 now which stops output after
```
info depth 17 currmove c3d5 currmovenumber 1
```
I ran it for ~30 minutes without furter output. Then I added some debug output in your search

```c    
    thread->nodes++;

    if (thread->nodes % 10000000 == 0)
    {
        printf("nodes: %"PRIu64"  depth: %d  height: %d\n", thread->nodes, depth, height);
        fflush(stdout);
    }

```
Seems that Ethereal searches at very high (selective) depth on this position:

```
...
nodes: 260000000  depth: 1  height: 47
nodes: 300000000  depth: 1  height: 54
nodes: 310000000  depth: 1  height: 74
nodes: 330000000  depth: 2  height: 64
nodes: 340000000  depth: 2  height: 66
nodes: 360000000  depth: 1  height: 74
nodes: 390000000  depth: 1  height: 67
nodes: 410000000  depth: 1  height: 78
...
```
Some extensions that are not limited?

**Comment by AndyGrant** [comment]
So, nice observation, and its (unfortunately) not a knew issue. The outputs below are from disabling all extensions. 

Ethereal is very aggressive in how extensions are applied. I've spent more time trying to limit them than I would like to share. I suppose these mate positions could likely be accounted for and adjust the extensions, but its not the kind of change to bring elo or appear as a simplification.

```
info depth 31 seldepth 32 score mate 48 time 6802 nodes 460973295 nps 67760000 tbhits 0
hashfull 52 pv c3e4 g1h1 e5f4 h1g1 f4g3 g1h1 e4f2 h1g1 g3d6 g1f1 d6h2 f1e1 f2e4 e1d1 h2e5 
d1e1 e5d4 e1f1 e4c3 f1e1 d4e3 e1f1 e3c5 f1e1 c3e4 e1d1 c5d4 d1e1 d4b6 e1d1 b6a5
```

```
info depth 71 seldepth 57 score mate 21 time 6072757 nodes 453974908712 nps 74755000 tbhits
0 hashfull 111 pv e5d6 g1h1 c3e4 h1g1 e4f2 g1f1 d6h2 f1e1 f2e4 e1d1 h2e5 d1c2 e4c5 c2d2 f3f2
d2d1 e5c3 d1c2 c3a5 c2d1 f2f1 d1c2 f1e2 c2c1 e2d3 c1d1 c5a4 d1c1 a5d2 c1b1 d3c3 b1a2 d2c1
a2b1 c3d2 b1a2 d2c2 a2a1 c1b2 a1a2 a4c3
```

**Comment by Matthies** [comment]
Okay, so it is no real problem, just some strange behaviour in some (probably) rare positions. So I will close this.
