### ISSUE TITLE
Neglected Pawn Recapture, immediately losing material?

### ISSUE THREAD

**Issue by TesseractA** [AndyGrant/Ethereal#88]
1R1Q4/2r3qk/3p2p1/3Pbp1p/8/p3N1PP/P4PK1/8 w - - 2 60

Ethereal plays Nxf5??

https://www.chess.com/computer-chess-championship#event=ccc10-quarterfinals&game=55

Nxf5 is throwing away a piece. Ethereal did not expect gxf5 after Nxf5. The evaluation appeared to be 0.0 then immediately dropped to -6 after gxf5 was played, black would gain +2  material directly from it. Not sure why really, could it be a hashing issue?

**Comment by AndyGrant** [comment]
I'm not sure, and the link you gave seems to not go to the Ethereal game for me. Likely Ethereal knew it was -6 before making Nxf5, but never finished resolving just how bad the move was, before playing it. I'm not concerned. 

Sorry for the late response. I've been in the hospital for a few weeks.

**Comment by TesseractA** [comment]
@AndyGrant It looks like cccc's links to archive games have some issues. Game 55 CCCC10; Here is the FEN: 
1R1Q4/2r3qk/3p2p1/3PbN1p/8/p5PP/P4PK1/8 b - - 0 60
This was move 60 of the game. Ethereal is playing as white.

Here is the PGN if necessary:
``1. d4 c5 2. d5 e6 3. c4 g6 4. e4 d6 5. Nf3 Bg7 6. Bd3 exd5 7. cxd5 Nf6 8. h3 c4 9. Qa4+ b5 10. Qxb5+ Nbd7 11. Qxc4 Nc5 12. Qc2 Nxd3+ 13. Qxd3 a5 14. Na3 O-O 15. Nc4 Ba6 16. Be3 Re8 17. O-O Nxe4 18. Nd4 Qh4 19. Rac1 Ng5 20. Bxg5 Qxg5 21. Nf3 Qf6 22. b3 a4 23. Qd2 Rab8 24. Qa5 Bxc4 25. bxc4 Ra8 26. Qd2 Reb8 27. Qd3 Rb2 28. Qa3 Bh6 29. Rb1 Rc2 30. Nh2 Bg7 31. Ng4 Qd8 32. Ne3 Rc3 33. Qb4 h5 34. Rfd1 Be5 35. Qb7 Kg7 36. Rd2 Rc8 37. Qa6 Ra3 38. Qb7 Rc3 39. Qa6 Ra8 40. Qc6 a3 41. Qb7 Ra4 42. Rdd1 Qf6 43. Qc8 Ra7 44. Re1 Kh7 45. Rb8 Rd3 46. Nf1 Rc3 47. Qg8+ Kh6 48. Ne3 Rd3 49. Qf8+ Kh7 50. Nf1 Rc7 51. g3 Rxc4 52. Re3 Rxe3 53. Nxe3 Rc7 54. Qg8+ Kh6 55. Qf8+ Kh7 56. Qg8+ Kh6 57. Qf8+ Qg7 58. Qd8 f5 59. Kg2 Kh7 60. Nxf5 gxf5 61. Qe8 Qf7 62. Qxf7+ Rxf7 63. Ra8 f4 64. gxf4 Rxf4 65. Rxa3 Rd4 66. Rb3 Kg6 67. Rc3 Rxd5 68. Rb3 Ra5 69. a3 Kf5 70. Rf3+ Ke6 71. Rd3 Ra4 72. Rd2 Rxa3 73. Rc2 d5 74. Rc6+ Bd6 75. Rb6 Ra4 76. Kf3 Rc4 77. Kg2 Kd7 78. h4 Rxh4 79. Rb3 Kc6 80. Rc3+ Rc4 81. Rf3 h4 82. Kf1 h3 83. Rxh3 Re4 84. Rh5 d4 85. Rh3 Kd5 86. Kg2 Kc4 87. Kg1 Re1+ 88. Kg2 Ra1 89. Rh4 Kc3 90. Rh5 d3 91. Rg5 d2 92. Rd5 Bb4 93. f4 Ba3 94. Kh3 Bb2 95. Kg2 d1=Q 96. Rxd1 Rxd1 97. Kf2 Kd3 98. Kg2 Bc1 99. Kf2 Bxf4 100. Kf3 Rg1 101. Kf2 Rg3 102. Ke1 Rf3 103. Kd1 Rf1# 0-1``
