### ISSUE TITLE
Ethereal should attempt to find a shorter mate in Syzygy positions

### ISSUE THREAD

**Issue by Alayan-stk-2** [AndyGrant/Ethereal#90]
```
    // If the root position can be found in the DTZ tablebases,
    // then we simply return the move recommended by Syzygy/Fathom.
```

The current code ensure that draws stay draws and wins stay wins, but it's pretty sad to see Ethereal make a mate announcement with 7 or 8 pieces on the board, then take 15 more moves to mate because DTZ is followed in 6-men syzygy positions.

**Comment by AndyGrant** [comment]
What do you suggest? Given a position which has a best-case result X, do a normal search. Before printing that move as the best move, see if the move maintains X. If it does not, choose another one. What would you like to see in the (rare?) event that Ethereal wants a move which fails to achieve X? It will be bizzare to see a depth 20 search for move A, followed by a ``bestmove B``

**Comment by Alayan-stk-2** [comment]
> Given a position which has a best-case result X, do a normal search. Before printing that move as the best move, see if the move maintains X. If it does not, choose another one.

Yes, I'm thinking of something along those lines.

> What would you like to see in the (rare?) event that Ethereal wants a move which fails to achieve X? It will be bizzare to see a depth 20 search for move A, followed by a `bestmove B`

The most important would be to still play a correct move that doesn't lose the theoretical game state. Also, we wouldn't want to display the wrong PV for move A of course.

But then, can't we use syzygy to prune at root moves that lose the theoretical game state from considerations ? Analogous to the uci excludemove logic, except TB probing gives us the move to exclude.

**Comment by Alayan-stk-2** [comment]
Fixed with https://github.com/AndyGrant/Ethereal/commit/4149e7f503599bc454d11b1a49f7665f2a8f153b
