### ISSUE TITLE
OS

### ISSUE THREAD

**Issue by iandoug** [AndyGrant/Ethereal#97]
Hi

Is this Windows-only?

Thanks, Ian

**Comment by AndyGrant** [comment]
Ian,
  
Ethereal works on Windows as well as on Linux and MacOS devices. I typically don't include binaires for Linux as I assume those users would prefer to compile their own.

**Comment by iandoug** [comment]
Hi
So noted, thanks .... appears to be compiled now, will test shortly. I see your engine is doing well on TCEC.

Thanks, Ian
