### ISSUE TITLE
Support for "searchmoves"?

### ISSUE THREAD

**Issue by LocutusOfPenguin** [AndyGrant/Ethereal#99]
Hi Andy,

do y plan to support this?

go movetime 100 searchmoves f2f3 a2a3
bestmove e2e4 ponder c7c5

I use this for "alternative move" at picochess, which is a great feature in my eyes.

Jürgen

**Comment by AndyGrant** [comment]
How would you like to see this done? For ``go movetime 100 searchmoves f2f3 a2a3`` would Ethereal do a normal search, but ONLY look at ``f2f3`` and ``a2a3``? Or would Ethereal do something more similar to a ``MultiPV=2`` search, and make sure to report scores for both ``f2f3`` and ``a2a3``?

**Comment by LocutusOfPenguin** [comment]
throw all other root-moves away (as if they are illegal).
so, not with multiPV.
Y might take a look at other engines, SF for example implements this (there are more).

I think, thats not that complicated (even thats easy said from me, haha).

**Comment by AndyGrant** [comment]
Implemented here: https://github.com/AndyGrant/Ethereal/commit/838e7738db93427801d94373ba8a5586f2c122ed Let me know if you have any issues.
